name: Deploy

on:
  push:
    branches: ["workflows/integration"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t santoshyadav88/next-js-app:latest

      - name: Push Docker image
        run: docker push santoshyadav88/next-js-app:latest
