name: Deploy

on:
  push:
    branches: ["workflow/integration"]
  # optional: allow manual runs
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t santoshyadav88/next-js-app:latest .

      - name: Push Docker image
        run: docker push santoshyadav88/next-js-app:latest
